name: New software
description: Tell us about some new software
title: "[New software]: "
labels: ["software", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to tell us about this software!
  - type: input
    id: name
    attributes:
      label: The software's name
      placeholder: My Sleep App
    validations:
      required: true
  - type: input
    id: description
    attributes:
      label: Description
      placeholder: What makes this project unique?
    validations:
      required: true
  - type: input
    id: home_page
    attributes:
      label: Home page
      description: Where can people find out about the project?
      placeholder: https://my-sleep-app.com/
    validations:
      required: true
  - type: input
    id: source_code
    attributes:
      label: Where can people get the source code?
      description: Where can people find your app?
      placeholder: https://github.com/my-sleep-app/
  - type: checkboxes
    id: platforms
    attributes:
      label: Which platforms does it support?
      options:
        - label: Windows
        - label: MacOS
        - label: Linux
        - label: Android
        - label: iOS
        - label: website
        - label: dedicated device (e.g. a watch)
        - label: other (specified below)
  - type: textarea
    id: other_platforms
    attributes:
      label: Other platforms
      description: List any other supported platforms here
      placeholder: |
        - NetBSD
        - Windows Mobile
        - Sega Genesis
  - type: dropdown
    id: business_model
    attributes:
      label: What is the app's business model?
      options:
        - Free (open source)
        - Free (closed source)
        - Ad-supported
        - Paid app with free trial
        - Paid
        - Device with free app
        - other (specified below)
  - type: input
    id: other_business_model
    attributes:
      label: Other business model
      description: If the app doesn't fit into an existing category
      placeholder: Website account with regular payments
  - type: textarea
    id: procedure
    attributes:
      label: Procedure
      placeholder: |
        1. [install the app](https://my-sleep-app.com/download)
        2. follow the on-screen instructions
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Gallery

        Please provide at least an in-app screenshot, usually showing whichever screen will be most interesting to a new user.

        If the app generates graphs, we would also like one screenshot for each of [our common sleep diaries](https://sleepdiary.github.io/resources/common_sleep_diaries/).  If you're not sure how, just upload what you can for now and we'll talk it through.

        Here are some specific requirements:

        * screenshots should be maximised if possible, and must not show anything other than the app itself
        * screenshots must not show personally-identifying information, such as a folder with your name in it

        And here are some tips:

        * for Windows apps, use [Snipping Tool](https://support.microsoft.com/en-us/windows/use-snipping-tool-to-capture-screenshots-00246869-1843-655f-f220-97299b865f6b)
        * for Android apps, [take a screenshot](https://support.google.com/android/answer/9075928?hl=en-GB)
        * for iOS apps [take a screenshot](https://support.apple.com/en-gb/HT200289)
    validations:
      required: true
  - type: textarea
    id: gallery
    attributes:
      label: Gallery
      description: Main screenshot and graphs based on common diaries
      placeholder: |
        Main screenshot
        Available at https://my-sleep-app.com/screenshot.png

        Screenshots for common sleep diaries
        See attached images (for instructions, see beneath this text box)

  - type: textarea
    id: comments
    attributes:
      label: Any other comments

  - type: markdown
    attributes:
      value: |
        ---

        Thanks!  We'll take a look and talk to you in a day or so.
